---
file: "9.1_Probabilidad-en-R_Conceptos.Rmd"
title: "Probabilidad en R: Conceptos"
author: "prof. dr. J. Zavala"
telegram: "https://t.me/jzavalar"
date: "2023-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
[https://rpubs.com/hllinas/R_Exp-Omega-Evento](https://rpubs.com/hllinas/R_Exp-Omega-Evento)

-----------
N.B. Este tutorial corresponde a una versión actualizada del tutorial de referencia del dr. Humberto LLinás, convertido a RMarkdown. Sólo se han actualizado algunos aspectos de Rmarkdown y LaTex, para la reproducción del mismo, sin errores, en 2023, desde RStudio.
-----------

PROBABILIDAD EN R
Experimento, espacio muestral y evento
Dr. rer. nat. Humberto LLinás Solano
Departamento de Matemáticas y Estadística, Universidad del Norte (Barranquilla, Colombia)

hllinas@uninorte.edu.co

Biographical sketch

26/08/21

Abstract

La teoría mencionada puede revisarse en el capítulo 2 de mis notas de clase que aparecen en el siguiente documento: 1.1. Estadística básica. En Rpubs:: toc se pueden ver otros documentos de posible interés.

hllinas
1 Paquetes

En R podemos encontrar diversas funciones para ello:

    “expand.grid” en el paquete “base”.
    “combn” en el paquete “combinat”.
    “permsn”, “tosscoin”, etc., en el paquete “prob”.

Para nuestros cálculos, utilizaremos la siguiente librería:

library(prob)   #A) Para analizar experimentos estadísticos

2 Experimento

Todo experimento se puede clasificar como se ilustra en la figura de abajo:
3 Espacio muestral

Teóricamente se simbolizará con Ω

. Revisaremos algunos ejemplos para encontrar los elementos de este conjunto.
3.0.1 Ejemplo: Lanzar monedas

Considere el experimento aleatorio de lanzar n veces una moneda. Los resultados elementales son H (head, cara) y T (tail, sello). Con la librería “prob”, Podemos hallar los elementos del espacio muestral con la función “tosscoin” (lanzamiento de monedas):

tosscoin(1)     #A) Espacio muestral con n=1 lanzamiento de una moneda

##   toss1
## 1     H
## 2     T

tosscoin(2)     #B) Espacio muestral con n=2 lanzamientos de una moneda

##   toss1 toss2
## 1     H     H
## 2     T     H
## 3     H     T
## 4     T     T

tosscoin(3)     #C) Espacio muestral con n=3 lanzamientos de una moneda

##   toss1 toss2 toss3
## 1     H     H     H
## 2     T     H     H
## 3     H     T     H
## 4     T     T     H
## 5     H     H     T
## 6     T     H     T
## 7     H     T     T
## 8     T     T     T

Para determinar el número de elementos que tiene el espacio muestral Ω

y el de la muestra, se puede utilizar la función “dim”:

Omega<- tosscoin(10)  #D) Espacio muestral con n=10 lanzamientos de una moneda
dim(Omega)            #E) Tamaños de Omega y de la muestra

## [1] 1024   10

3.0.2 Ejemplo: Lanzar dados

Ahora considere el experimento aleatorio de lanzar n veces un dado. Los resultados elementales son 1, 2, 3,4, 5 y 6. Con la librería “prob”, Podemos hallar los elementos del espacio muestral con la función “rolldie” (lanzamiento de dados):

Omega<- rolldie(2); Omega    #F) Espacio muestral con n=2 lanzamientos de un dado

##    X1 X2
## 1   1  1
## 2   2  1
## 3   3  1
## 4   4  1
## 5   5  1
## 6   6  1
## 7   1  2
## 8   2  2
## 9   3  2
## 10  4  2
## 11  5  2
## 12  6  2
## 13  1  3
## 14  2  3
## 15  3  3
## 16  4  3
## 17  5  3
## 18  6  3
## 19  1  4
## 20  2  4
## 21  3  4
## 22  4  4
## 23  5  4
## 24  6  4
## 25  1  5
## 26  2  5
## 27  3  5
## 28  4  5
## 29  5  5
## 30  6  5
## 31  1  6
## 32  2  6
## 33  3  6
## 34  4  6
## 35  5  6
## 36  6  6

dim(Omega)                   #G) Tamaños de Omega y de la muestra

## [1] 36  2

4 Evento

Para obtener un evento de Ω

en R, podemos extraer filas usando el operador [].
4.0.1 Ejemplo: Lanzar monedas

Omega <- tosscoin(3); Omega    #A) Espacio muestral

##   toss1 toss2 toss3
## 1     H     H     H
## 2     T     H     H
## 3     H     T     H
## 4     T     T     H
## 5     H     H     T
## 6     T     H     T
## 7     H     T     T
## 8     T     T     T

dim(Omega)                     #B) Tamaños de Omega y de la muestra

## [1] 8 3

B<- Omega[1:4, ]; B            #C) Evento B

##   toss1 toss2 toss3
## 1     H     H     H
## 2     T     H     H
## 3     H     T     H
## 4     T     T     H

C<- Omega[c(1,4),]; C          #D) Evento C

##   toss1 toss2 toss3
## 1     H     H     H
## 4     T     T     H

4.0.2 Ejemplo: Lanzar dados

Omega <- rolldie(2); head(Omega)          #E) Espacio muestral

##   X1 X2
## 1  1  1
## 2  2  1
## 3  3  1
## 4  4  1
## 5  5  1
## 6  6  1

dim(Omega)                                #F) Tamaños de Omega y de la muestra

## [1] 36  2

G <- subset(Omega, X1 + X2 > 10); G       #G) Evento G

##    X1 X2
## 30  6  5
## 35  5  6
## 36  6  6

5 Funciones para encontrar subconjuntos
5.1 La función (b %in% a)

Retornará TRUE si el valor de un vector b está en algún lugar dentro de otro vector a.

x <- 1:6          #A)
y <- 2:4          #B)
z <- c(2,2,4)     #C)

y %in% x          #D)

## [1] TRUE TRUE TRUE

x %in% y          #E)

## [1] FALSE  TRUE  TRUE  TRUE FALSE FALSE

x %in% z          #F)

## [1] FALSE  TRUE FALSE  TRUE FALSE FALSE

5.2 La función all(b %in% a)

La función retornará TRUE si todos los valores del vector b están dentro de otro vector a.

all(y %in% x)          #G)

## [1] TRUE

all(x %in% y)          #H)

## [1] FALSE

all(x %in% z)          #I)

## [1] FALSE

5.3 La función isin(a,b)

La función retornará TRUE si cada elemento de b está presente en el vector a, contando multiplicidades.

isin(y, x)          #J)

## [1] FALSE

isin(x, y)          #K)

## [1] TRUE

isin(x, y)          #L)

## [1] TRUE

5.4 La función isin(a,b) con opción ordered

Hay un argumento opcional que prueba si un elemento del vector b aparece en el a en el mismo orden en que ellos aparecen en b. Por ejemplo:

isin(x, c(2, 3, 4), ordered = TRUE)          #M)

## [1] TRUE

isin(x, c(3, 2, 4), ordered = TRUE)          #N)

## [1] FALSE

5.5 La función isin(a,b) para construir eventos

La función “isin” se puede aplicar a cada fila del data frama para encontrar el evento deseado. Por ejemplo,

Omega <- rolldie(3); head(Omega)          #O) Dados, n=3

##   X1 X2 X3
## 1  1  1  1
## 2  2  1  1
## 3  3  1  1
## 4  4  1  1
## 5  5  1  1
## 6  6  1  1

dim(Omega)                                #P) Tamaños de Omega y muestra

## [1] 216   3

A <- subset(Omega, isin(Omega, c(2, 1), ordered = TRUE)); A      #Q) Evento

##     X1 X2 X3
## 2    2  1  1
## 7    1  2  1
## 8    2  2  1
## 9    3  2  1
## 10   4  2  1
## 11   5  2  1
## 12   6  2  1
## 14   2  3  1
## 20   2  4  1
## 26   2  5  1
## 32   2  6  1
## 38   2  1  2
## 74   2  1  3
## 110  2  1  4
## 146  2  1  5
## 182  2  1  6

dim(A)          #R) Tamaños del evento y de la muestra

## [1] 16  3

6 Operaciones con conjuntos

La tabla de abajo resume las operaciones que se pueden calcular con R:
Operación 	Código
Unión (A∪B
) 	union(A,B)
Intersección (A∩B
) 	intersect(A,B)
Diferencia (A∖B
) 	setdiff(A,B)
Igualdad (A=B
) 	setequal(A,B)

Revisemos algunos ejemplos:

Omega <- rolldie(2); head(Omega)

##   X1 X2
## 1  1  1
## 2  2  1
## 3  3  1
## 4  4  1
## 5  5  1
## 6  6  1

A <- subset(Omega, isin(Omega, c(2, 1), ordered = TRUE)); A      #A) Evento A

##   X1 X2
## 2  2  1

B <- subset(Omega, isin(Omega, c(1, 2), ordered = FALSE)); B     #B)Evento B

##   X1 X2
## 2  2  1
## 7  1  2

union(A,B)          #C) Unión

##   X1 X2
## 2  2  1
## 7  1  2

intersect(A,B)      #D) Intersección

##   X1 X2
## 2  2  1

setdiff(A,B)        #E) Diferencia A-B

## [1] X1 X2
## <0 rows> (or 0-length row.names)

setdiff(B,A)        #F) Diferencia B-A

##   X1 X2
## 7  1  2

setequal(A,B)       #G) Igualdad

## [1] FALSE

7 Ejercicios

Dado el experimento aleatorio, encuentre los elementos de los eventos indicados abajo, el número de elementos que contiene y el tamaño de la muestra. Para ello, debe crear un nuevo documento R Markdown. Explique siempre sus afirmaciones y los códigos utilizados. Interprete los resultados hallados.

    Experimento: Un dado se lanza dos veces.
        Ω

: El espacio muestral.
Evento B: La suma de los números es 7. Sugerencia: utilizar == para indicar el símbolo de igualdad.
Evento C: La suma de los números es por lo menos un 11.
Evento D: La suma de los números es a lo más un 2.
Evento E: Se obtiene un doble. Sugerencia: utilizar == para indicar el símbolo de igualdad.
Evento F: No se obtiene un doble. Sugerencia: utilizar != para indicar el símbolo de diferente.
Unión de B y F.
Interseción de C y E.
Diferencia C-F.
Evento J: Unión de E y F. Verifique en R si J es igual a Ω

    .
    Intersección de C y D.
    Diferencia de B y D.
    Evento M: Contiene los elementos de la forma (3,4), ordenados. Sugerencia: utilizar la función isin().
    Evento N: Contiene los elementos de la forma (3,4), no ordenados. Sugerencia: utilizar la función isin(). Compare con el evento M.
    Evento O: Uno cualquiera obtenido al aplicar la función corchete.

Experimento: Una moneda se lanza cuatro veces.

    Ω

: El espacio muestral.
Evento B: Las primeras 2 observaciones. Utilizar la función corchete.
Evento C: Las primeras 5 observaciones. Utilizar la función corchete.
Unión de B y C.
Intersección de B y C.
Diferencia B-C.
Diferencia C-B.
Evento H: El complemento de B.
Evento I: El complemento de C
Intersección de B y H.
Evento K: Unión de C y I. Verifique en R si K es igual a Ω

        .
        Evento L: Salgan 2 caras. Sugerencia: utilizar la función isin().
        Evento M: Salgan 3 caras. Sugerencia: utilizar la función isin().

8 Enlaces y materiales de ayuda

    IPSUR (Introduction to Probability and Statistics Using R): https://www.nongnu.org/ipsur/

    LLinás, H.; Rojas, C., Estadística descriptiva y distribuciones de probabilidad. Barranquilla: Ediciones Uninorte, 2005.
