---
file: "9.2_Probabilidad-en-R_Muestreo.Rmd"
title: "Probabilidad en R: Muestreo"
author: "prof. dr. J. Zavala"
telegram: "https://t.me/jzavalar"
date: "2023-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[https://rpubs.com/hllinas/R_Urnas](https://rpubs.com/hllinas/R_Urnas)

PROBABILIDAD EN R
Muestreo desde una urna
Dr. rer. nat. Humberto LLinás Solano
Departamento de Matemáticas y Estadística, Universidad del Norte (Barranquilla, Colombia)

hllinas@uninorte.edu.co

Biographical sketch

26/08/21

Abstract

La teoría mencionada puede revisarse en el capítulo 2 de mis notas de clase que aparecen en el siguiente documento: 1.1. Estadística básica. En Rpubs:: toc se pueden ver otros documentos de posible interés.

hllinas
1 Paquetes

En R podemos encontrar diversas funciones para ello:

    “expand.grid” en el paquete “base”.
    “combn” en el paquete “combinat”.
    “permsn”, “tosscoin”, etc., en el paquete “prob”.

Para nuestros cálculos, utilizaremos la siguiente librería:

library(prob)   #A) Para los modelos de urna

2 La función “urnsamples”

El paquete “prob” realiza el muestreo de urnas con la función “urnsamples”, que tiene los siguientes argumentos:

    x: Representa la urna desde la cual se va a hacer el muestreo.
    size: Tamaño de la muestra.
    replace: TRUE, si es con reemplazo; y FALSE, sin reemplazo.
    ordered: TRUE, si es con orden; y FALSE, sin orden.

3 Muestreo con orden y con reemplazo

Supongamos que tenemos una caja con tres (3) elementos, etiquetados con 1, 2 y 3, respectivamente y que vamos a seleccionar una muestra de tamaño 2 de la caja (con orden y con reemplazo).

urnsamples(1:3, size = 2, ordered = TRUE, replace = TRUE)    #A) Con orden y con reemplazo

##   X1 X2
## 1  1  1
## 2  2  1
## 3  3  1
## 4  1  2
## 5  2  2
## 6  3  2
## 7  1  3
## 8  2  3
## 9  3  3

Este experimento es equivalente a lanzar dos veces un dado de 3 caras, lo que podríamos haber logrado con:

rolldie (2, nsides = 3)      #B) Dado de tres caras

4 Muestreo con orden y sin reemplazo

Supongamos que tenemos una caja con tres (3) elementos, etiquetados con 1, 2 y 3, respectivamente y que vamos a seleccionar una muestra de tamaño 2 de la caja (con orden y sin reemplazo).

urnsamples(1:3, size = 2, ordered = TRUE, replace = FALSE)    #C) Con orden y sin reemplazo

##   X1 X2
## 1  1  2
## 2  2  1
## 3  1  3
## 4  3  1
## 5  2  3
## 6  3  2

5 Muestreo sin orden y con reemplazo

Supongamos que tenemos una caja con tres (3) elementos, etiquetados con 1, 2 y 3, respectivamente y que vamos a seleccionar una muestra de tamaño 2 de la caja (sin orden y con reemplazo).

urnsamples(1:3, size = 2, ordered = FALSE, replace = TRUE)     #D) Sin orden y con reemplazo

##   X1 X2
## 1  1  1
## 2  1  2
## 3  1  3
## 4  2  2
## 5  2  3
## 6  3  3

6 Muestreo sin orden y sin reemplazo

Supongamos que tenemos una caja con tres (3) elementos, etiquetados con 1, 2 y 3, respectivamente y que vamos a seleccionar una muestra de tamaño 2 de la caja (con orden y sin reemplazo).

urnsamples(1:3, size = 2, ordered = FALSE, replace = FALSE)     #E) Sin orden y con reemplazo

##   X1 X2
## 1  1  2
## 2  1  3
## 3  2  3

7 Ejercicios

Dado el experimento aleatorio, encuentre los elementos de Ω

(el espacio muestral), el número de elementos que contiene y el tamaño de la muestra. Debe utilizar las funciones de esta sección. Crear un nuevo documento R Markdown. Explique siempre sus afirmaciones y los códigos utilizados. Interprete los resultados hallados.

    Una caja tiene 10 bolas. Se sacan 2 bolas:

        Sin orden y sin reemplazo.

        Con orden y sin reemplazo.

        Sin orden y con reemplazo.

        Con orden y con reemplazo.

    De un total de 8 facturas diferentes, un gerente selecciona 5 con el fin de:

        Ordenarlas en un lugar especifico de su escritorio.

        Colocarlas en un lugar especifico de su escritorio.

    Una urna contiene 7 fichas. ¿Cuáles y cuántas son las distintas maneras de seleccionar 2 fichas:

        Sin orden y sin reemplazo.

        Con orden y sin reemplazo.

        Sin orden y con reemplazo.

        Con orden y con reemplazo.

    Formar un grupo de tamaño 5 de entre 12 personas.

    Sentar 6 personas en un sofá que sólo tiene disponible 3 puestos.

    Un consumidor ordena, por orden de preferencia, el sabor de 5 marcas de cerveza.

    Formar números de 3 cifras sin repetición con los dígitos 8, 2, 5, 4 y 7.

    Una pieza de un radio puede ser comprado de cualquiera de 6 proveedores. Se escogen 3 de los 6 proveedores.

8 Enlaces y materiales de ayuda

    IPSUR (Introduction to Probability and Statistics Using R): https://www.nongnu.org/ipsur/

    LLinás, H.; Rojas, C., Estadística descriptiva y distribuciones de probabilidad. Barranquilla: Ediciones Uninorte, 2005.
