---
file: 9.3_Probabilidad-en-R_Conteo.Rmd
title: "Probabilidad en R: Conteo"
author: "prof. dr. J. Zavala"
telegram: https://t.me/jzavalar
date: "2023-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
[https://rpubs.com/hllinas/R_Conteo](https://rpubs.com/hllinas/R_Conteo)


PROBABILIDAD EN R
Técnicas de conteo
Dr. rer. nat. Humberto LLinás Solano
Departamento de Matemáticas y Estadística, Universidad del Norte (Barranquilla, Colombia)

hllinas@uninorte.edu.co

Biographical sketch

26/08/21

Abstract

La teoría mencionada puede revisarse en el capítulo 2 de mis notas de clase que aparecen en el siguiente documento: 1.1. Estadística básica. En Rpubs:: toc se pueden ver otros documentos de posible interés.

hllinas
1 Paquetes

En R podemos encontrar diversas funciones para ello:

    “expand.grid” en el paquete “base”.
    “combn” en el paquete “combinat”.
    “permsn”, “tosscoin”, etc., en el paquete “prob”.

Para nuestros cálculos, utilizaremos la siguiente librería:

library(prob)   #A) Para contar los elementos de un evento

2 La función “nsamp”

En el paquete “prob”, encontramos esta función. Ella calcula el número de filas en un espacio muestral encontrado por la función “urnsamples”, sin necesidad de listar los elementos del espacio. Los argumentos son:

    x: Representa la urna desde la cual se va a hacer el muestreo.
    size: Tamaño de la muestra.
    replace: TRUE, si es con reemplazo; y FALSE, sin reemplazo.
    ordered: TRUE, si es con orden; y FALSE, sin orden.

3 Muestreo ordenado (permutaciones)
3.0.1 Definición

Recuerde una permutación es un arreglo ordenado de una cantidad finita de objetos distintos. El número de formas en que se puede seleccionar una permutación de k sujetos de una población que tiene n sujetos distinguibles depende el tipo de muestreo.

    Si el muestreo es hecho con reemplazo, el número de permutaciones es:
    nk

Si el muestreo es hecho sin reemplazo, el número de permutaciones es:
n!(n−k)!

Si el muestreo es hecho sin reemplazo y n=k
, el número de permutaciones es
n!

El símbolo n!

se lee “n factorial” y, en R, es computado is computed con el comando factorial(n). Algunos valores factoriales son los siguientes:

    0!:=1

,
1!=1
,
2!=2⋅1=2
,
3!=3⋅2⋅1=6
,
4!=4⋅3⋅2⋅1;=24

    .

3.0.2 Ejemplo

Si se le pide a un consumidor que ordene, por orden de preferencia, el sabor de cinco marcas de cerveza, entonces el número de permutaciones que resultan será 5!=120

. Con R se puede calcular de dos maneras:

factorial(5)                   #A) Factorial
nsamp(n = 5, k = 5, replace = FALSE, ordered = TRUE)    #B) Sin reemplazo, con orden    

3.0.3 Ejemplo

Supongamos que se quiere seleccionar (con orden) una muestra de tamaño 2 de una urna con 3 elementos disponibles. Si es con reemplazo, tendríamos 9 posibilidades, pero, sin reemplazo, solo 6. Con R:

nsamp(n = 3, k = 2, replace = TRUE, ordered = TRUE)     #C) Con reemplazo, con orden
nsamp(n = 3, k = 2, replace = FALSE, ordered = TRUE)    #D) Sin reemplazo, con orden    

3.0.4 Ejemplo

El número de formas diferentes en que se pueden sentar 8 alumnos en una oficina con sólo 5 sillas es 8!(8−5)!=6720

. Con R:

nsamp(n = 8, k = 5, replace = FALSE, ordered = TRUE)     #E) Sin reemplazo, con orden

4 Muestreo no ordenado (combinaciones)

Recuerde una combinación es un arreglo no ordenado de una cantidad finita de objetos distintos. El número de formas en que se puede seleccionar una combinación de k sujetos de una población que tiene n sujetos distinguibles es:
Muestreo 	ordered = FALSE
replace=TRUE 	(n+k−1k)
replace=FALSE 	(nk)

El símbolo (nk)

se llama coeficiente binomial y, en R, es computado con el comando choose(n,k). Se define como
(nk):=n!k!(n−k)!
, siendo (n0):=1
.
4.0.1 Ejemplo

Un comité, de 3 mujeres de un grupo de 8, se puede escoger de (83)=56

maneras. En R se puede calcular de dos maneras:

choose(8,3)                                             #A) Coeficiente binomial
nsamp(n = 8, k = 3, replace = FALSE, ordered = FALSE)   #B) Sin reemplazo, sin orden

4.0.2 Ejemplo

Supongamos que se quiere seleccionar (sin orden) una muestra de tamaño 2 de una urna con 3 elementos disponibles. Si es sin reemplazo, tendríamos 3 posibilidades, pero, con reemplazo, solo 6. Con R:

nsamp(n = 3, k = 2, replace = FALSE, ordered = FALSE)   #C) Sin reemplazo, sin orden
nsamp(n = 3, k = 2, replace = TRUE, ordered = FALSE)    #D) Con reemplazo, sin orden

5 El teorema fundamental del conteo

Un beneficio de “nsamp” es podemos obtener un vector de respuestas numéricas (en vez de un solo número) cuando asignamos un vector de valores a n
, k

, replace, and ordered.
5.0.1 Ejemplo

Cuatro libros distintos de matemáticas, seis diferentes de física y dos diferentes de química se colocan en un estante. Determinar el número de formas distintas de ordenar los 12 libros si los libros de cada asignatura deben estar todos juntos.

SOLUCIÓN:

Los libros de matemáticas pueden ordenarse de 4!=24
formas, los de física de 6!=720 formas y los de química de 2!=2

formas. En R:

M <- factorial(4)    #A) Matemática
f <- factorial(6)    #B) Física
Q <- factorial(2)    #C) Química

Los tres grupos se pueden ordenar de 3!=6

formas. En R:

G <- factorial(3)    #D) Los tres grupos de libros

Por consiguiente, por el teorema fundamental del conteo, el número posible de maneras de ordenar los libros es (los libros de cada asignatura deben estar todos juntos):
4!6!2!3!=207.360

En R:

M*f*Q*G  #E) Permutación buscada

## [1] 207360

5.0.2 Ejemplo

De un total de 5 matemáticos y 7 físicos se forma un comité de 2 matemáticos y 3 físicos. El objetivo ahora es determinar el número de posible maneras puede formarlo si un físico determinado debe pertenecer al comité. Entonces:

SOLUCIÓN:

Tenemos que 2 matemáticos (de un total de 5) pueden elegirse de (52)=10
maneras y que 2 físicos restantes (de un total de 6) pueden elegirse de (62)=15

maneras. En R:

M<- choose(5,2)     #A) Matemáticos
F<- choose(6,2)     #B) Físicos

Por consiguiente, el número total de selecciones posibles es 10⋅15=150

. En R:

M*F        #C) Combinación buscada

## [1] 150

6 Ejercicios

Dado el experimento aleatorio, encuentre los elementos de Ω

(el espacio muestral), el número de elementos que contiene y el tamaño de la muestra. Debe utilizar las funciones de esta sección. Crear un nuevo documento R Markdown. Explique siempre sus afirmaciones y los códigos utilizados. Interprete los resultados hallados.

NOTA: Al final de la sección 2.2 de la referencia 2 (ver abajo), se pueden revisar más ejercicios.

    Una caja tiene 10 bolas. Se sacan 2 bolas:

        Sin orden y sin reemplazo.

        Con orden y sin reemplazo.

        Sin orden y con reemplazo.

        Con orden y con reemplazo.

    De un total de 8 facturas diferentes, un gerente selecciona 5 con el fin de:

        Ordenarlas en un lugar especifico de su escritorio.

        Colocarlas en un lugar especifico de su escritorio.

    Una urna contiene 7 fichas. ¿Cuáles y cuántas son las distintas maneras de seleccionar 2 fichas:

        Sin orden y sin reemplazo.

        Con orden y sin reemplazo.

        Sin orden y con reemplazo.

        Con orden y con reemplazo.

    Formar un grupo de tamaño 5 de entre 12 personas.

    Sentar 6 personas en un sofá que sólo tiene disponible 3 puestos.

    Un consumidor ordena, por orden de preferencia, el sabor de 5 marcas de cerveza.

    Formar números de 3 cifras sin repetición con los dígitos 8, 2, 5, 4 y 7.

    Una pieza de un radio puede ser comprado de cualquiera de 6 proveedores. Se escogen 3 de los 6 proveedores.

    Cuatro libros distintos de matemáticas, seis diferentes de física y dos diferentes de química se colocan en un estante. ¿De cuántas formas distintas es posible ordenarlos si:

        Los libros de cada asignatura deben estar todos juntos?

        Solamente los libros de matemáticas deben estar juntos?

    En un reinado mundial de la belleza, el jurado debe elegir, de un total de cinco finalistas, a la nueva reina. ¿De cuántas formas se pueden seleccionar:

        Reina y virreina?

        Reina, virreina y primera princesa?

        Dos candidatas para ser reina?

    En un estudio médico, los pacientes se clasifican de acuerdo a su peso (liviano, normal, pesado) y estatura (medio bajo, bajo, alto y medio alto). Enumere las diferentes posibilidades en las que un paciente se puede clasificar. ¿Cuántas posibilidades hay?

    Si un experimento consiste en lanzar un dado, luego, lanzar una moneda y después escoger al azar una letra de nuestro alfabeto, ¿cuántos elementos tiene el espacio muestral correspondiente? (Suponga que nuestro alfabeto tiene 27 letras).

    Los estudiantes de un curso de estadística se clasifican como estudiantes de administración, economía o ingeniería; como repitente o no repitente y también como hombre o mujer. Encuentre el número total de clasificaciones posibles para los estudiantes de dicho curso.

    Una persona ha visto un accidente de tránsito cuyo culpable huyó. A pesar de esto le dice a la Policía que la placa del carro en el que viajaba el culpable tenía tres letras (de las cuales las dos primeras eran C y A) y tres dígitos (de los cuales el último era 0). Encuentre el número máximo de placas de carro que la Policía debe verificar bajo cada una de las siguientes condiciones (nuestro alfabeto tiene 27 letras):

        Las tres letras son diferentes y los tres dígitos también.

        Las tres letras son diferentes y los dos dígitos que faltan son diferentes entre sí.

        La letra que hace falta es diferente de la A y los dígitos que hacen falta son diferentes e impares.

    De un total de 6 matemáticos y 8 físicos se forma un comité de 2 matemáticos y 3 físicos. ¿De cuántas maneras puede formarse si:

        Puede pertenecer a él cualquier matemático y físico?

        Un físico determinado debe pertenecer al comité?

        Dos matemáticos determinados no pueden pertenecer al comité?

7 Enlaces y materiales de ayuda

    IPSUR (Introduction to Probability and Statistics Using R): https://www.nongnu.org/ipsur/

    LLinás, H.; Rojas, C., Estadística descriptiva y distribuciones de probabilidad. Barranquilla: Ediciones Uninorte, 2005.

